spring:
  profiles:
    activate: local
    group:
      local:
        - common
        - h2_database
        - port_8080
      production-set1:
        - common
        - maria_database
        - port_8081
      production-set2:
        - common
        - maria_database
        - port_8082

---

spring:
  config:
    activate:
      on-profile: common
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  security:
    user:
      password: 1234
  mvc:
    static-path-pattern: /static/**

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  paths-to-match: /**
  swagger-ui:
    path: /api/
    display-request-duration: true
    groups-order: desc
    operations-sorter: alpha
    disable-swagger-default-url: true
  api-docs:
    groups:
      enabled: true

# logging ???
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace

jwt:
  header: Authorization
  #HS512 ????? ??? ??? ??? 512bit, ? 64byte ??? secret key? ???? ??.
  secret: ${secret}

  token:
    token-validity-in-seconds: 864000 # ttl (?)
    access-token-expiration-sec: 18000
    refresh-token-expiration-sec: 1209600

management:
  endpoints:
    web:
      base-path: /api/actuator

cloud:
  aws:
    s3:
      bucket: ${bucket}
      stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${s3.accessKey}
      secretKey: ${s3.secretKey}

---

spring:
  config:
    activate:
      on-profile: h2_database
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2
      port: 6379
      host: 127.0.0.1
      password: 1234

---

spring:
  config:
    activate:
      on-profile: maria_database
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}/S09P22E105?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 10
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
      data-source-properties:
        rewriteBatchedStatements: true
  data:
    redis:
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2
      port: 6379
      host: j9e105.p.ssafy.io
      password: 1234

---

spring:
  config:
    activate:
      on-profile: port_8080

server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: port_8081
  data:
    kakao-redirectUrl: https://j9e105.p.ssafy.io/oauth/callback/kakao

server:
  port: 8081

---

spring:
  config:
    activate:
      on-profile: port_8082
  data:
    kakao-redirectUrl: http://localhost:5173/oauth/callback/kakao

server:
  port: 8082


