server:
  port: 8080

spring:
  ########## method ##########
#  profiles:
#    active: prod
  ############################

 jpa:
   hibernate:
     ddl-auto: create
   properties:
     hibernate:
       format_sql: true
       show_sql: true
 datasource:
   url: jdbc:h2:tcp://localhost/~/test
   username: sa
   password:
   driver-class-name: org.h2.Driver

 h2:
   console:
     enabled: true
     path: /h2-console

 security:
   user:
     password: 1234

 data:
   redis:
     lettuce:
       pool:
         max-active: 10
         max-idle: 10
         min-idle: 2
     port: 6379
     host: 127.0.0.1
     password: 1234

 mvc:
   static-path-pattern: /static/**

# ??? ??
springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  paths-to-match: /**
  swagger-ui:
    path: /
    display-request-duration: true
    groups-order: desc
    operations-sorter: alpha
    disable-swagger-default-url: true
  api-docs:
    groups:
      enabled: true

# logging ???
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace


jwt:
  header: Authorization
  #HS512 ????? ??? ??? ??? 512bit, ? 64byte ??? secret key? ???? ??.
  secret: ${secret}

  token:
    token-validity-in-seconds: 86400 # ttl (?)
    access-token-expiration-sec: 1800
    refresh-token-expiration-sec: 1209600

